---
- hosts: all
  become: yes

  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

    - name: Install MongoDB
      dnf:
        name: mongodb-org
        state: present

    - name: Enable MongoDB
      systemd:
        name: mongod
        enabled: yes
        state: started
