---
- hosts: all
  become: yes

  tasks:

    - name: Add MongoDB Repository
      copy:
        dest: /etc/yum.repos.d/mongodb-org-8.0.repo
        content: |
          [mongodb-org-8.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/8.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-8.0.asc

    - name: Clean dnf cache
      command: dnf clean all

    - name: Build cache
      command: dnf makecache

    - name: Install MongoDB
      dnf:
        name: mongodb-org
        state: present

    - name: Enable MongoDB
      systemd:
        name: mongod
        enabled: yes
        state: started
